services:
  db:
    environment:
      POSTGRES_USER: SplitIt
      POSTGRES_PASSWORD: SplitItProject123
      POSTGRES_DB: SplitItdb
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: src/SplitIt.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=SplitItdb;Username=SplitIt;Password=SplitItProject123
    ports:
      - "5000:8080"
    depends_on:
      - db