services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: SplitIt
      POSTGRES_PASSWORD: SplitItProject123
      POSTGRES_DB: SplitItdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: